### ISSUE TITLE
Invalid memory address or nil pointer dereference on M1

### ISSUE THREAD

**Issue by MilanVives** [ruoshan/autoportforward#15]
```
~ ➤ docker run -d --name redis redis
ae44475c8835158e4c1d36406de38048b3b797e49f5f86a80e23f3e330b89c9f
~ ➤ apf redis

*  ==> : Forwarding local listening ports to (==>) remote ports
*  <== : Forwarding to local ports from (<==) remote listening ports (use -r option)

Forwarding: []panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x102cdff34]

goroutine 8 [running]:
io.ReadAtLeast({0x0, 0x0}, {0x140000ae00a, 0x3, 0x3}, 0x3)
	/opt/hostedtoolcache/go/1.17.5/x64/src/io/io.go:328 +0x74
io.ReadFull(...)
	/opt/hostedtoolcache/go/1.17.5/x64/src/io/io.go:347
github.com/ruoshan/autoportforward/manager.(*Manager).receivingLoop(0x14000066000)
	/home/runner/work/autoportforward/autoportforward/manager/manager.go:86 +0xb8
created by github.com/ruoshan/autoportforward/manager.(*Manager).Run
	/home/runner/work/autoportforward/autoportforward/manager/manager.go:74 +0x54
~ ➤
```

**Comment by ruoshan** [comment]
Hey @MilanVives , thank you for reporting this issue. I just add some debug lines in the latest main branch to debug this issue. Can you help me build a new binary and see what it prints?

To build this app, you need to:
- clone this repo
- and run `./build.sh`
- the new binary will be placed in the top directory of the repo.

Also, you can enable the logging by using `./apf -d`. the log files are located at `/tmp/autoportforward.log` both on the host and in the container. Appreciate it if you can post them back here.

**Comment by MilanVives** [comment]
Hi @ruoshan, thank you for the great work and also of taking the time to follow up with the issues. 
Problem seems solved in the latest build. 

```
autoportforward ➤ docker ps                                                                           git:main
CONTAINER ID   IMAGE     COMMAND                  CREATED        STATUS        PORTS      NAMES
ae44475c8835   redis     "docker-entrypoint.s…"   17 hours ago   Up 17 hours   6379/tcp   redis
autoportforward ➤ ./apf redis                                                                         git:main

*  ==> : Forwarding local listening ports to (==>) remote ports
*  <== : Forwarding to local ports from (<==) remote listening ports (use -r option)

Forwarding: [6379 ==> 6379]
```

```
autoportforward ➤ sudo netstat -ta | grep 6379                                                        git:main
tcp4       0      0  *.6379                 *.*                    LISTEN
autoportforward ➤
```

I will runs some further tests just to be sure but looks very promising. Great work!
